# Generated by Django 2.0.2 on 2018-07-18 12:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, verbose_name='好评率')),
                ('name', models.CharField(max_length=50, verbose_name='商品名')),
                ('sellCount', models.IntegerField(default=0, verbose_name='商品销售量')),
                ('oldPrice', models.IntegerField(default=0, verbose_name='市场价格')),
                ('price', models.IntegerField(default=0, verbose_name='本店价格')),
                ('description', models.TextField(max_length=140, verbose_name='商品类别描述')),
                ('info', models.TextField(max_length=140, verbose_name='商品简短描述')),
                ('image', models.TextField(blank=True, null=True, verbose_name='大图')),
                ('icon', models.TextField(blank=True, null=True, verbose_name='小图')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
            },
        ),
        migrations.CreateModel(
            name='Kinds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='类别名', max_length=30, verbose_name='分类名称')),
                ('type', models.SmallIntegerField(default=-1, verbose_name='暂时不知')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '商品类别',
                'verbose_name_plural': '商品类别',
            },
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=140, verbose_name='评论内容')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='goods/images/', verbose_name='小图')),
                ('rateType', models.IntegerField(default=0, verbose_name='不明')),
                ('rateTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('score', models.IntegerField(default=0, verbose_name='评价星数')),
                ('recommend', models.CharField(max_length=100, verbose_name='评论者id')),
                ('foods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.Foods', verbose_name='商品id')),
            ],
            options={
                'verbose_name': '评论信息',
                'verbose_name_plural': '评论信息',
            },
        ),
    ]
