# Generated by Django 2.0.2 on 2018-07-18 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='amazon_goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='无', max_length=255, verbose_name='商品名称')),
                ('price', models.CharField(blank=True, default='无', max_length=255, verbose_name='商品价格')),
                ('goal_price', models.CharField(blank=True, default='0', max_length=255, verbose_name='商品预期价格')),
                ('url', models.CharField(blank=True, default='无', max_length=255, verbose_name='商品url')),
                ('imgurl', models.CharField(blank=True, default='无', max_length=255, verbose_name='商品图片url')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'amazon_goods',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='big_kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='大类名')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'big_kind',
                'ordering': ('created',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='商品名')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='链接')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'goods',
                'ordering': ('created',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProxyIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50, verbose_name='ip地址')),
                ('port', models.CharField(max_length=10, verbose_name='端口号')),
                ('speed', models.IntegerField(verbose_name='网速')),
                ('proxy_type', models.CharField(default='HTTP', max_length=10, verbose_name='代理类型')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'proxy_ip',
                'ordering': ('created',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='small_kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='小类名')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('big', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='big_id', to='spiders.big_kind', verbose_name='大类Id')),
            ],
            options={
                'db_table': 'small_kind',
                'ordering': ('created',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='tiny_kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='具体类名')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('small', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='small_id', to='spiders.small_kind', verbose_name='小类Id')),
            ],
            options={
                'db_table': 'tiny_kind',
                'ordering': ('created',),
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='tiny',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiny_id', to='spiders.tiny_kind', verbose_name='具体类Id'),
        ),
        migrations.AlterUniqueTogether(
            name='amazon_goods',
            unique_together={('name',)},
        ),
    ]
