# Generated by Django 2.0.2 on 2018-07-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazon_goods',
            name='status',
            field=models.SmallIntegerField(default=0, verbose_name='记录状态'),
        ),
    ]
