# Generated by Django 2.0.2 on 2018-07-18 12:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='订单编号')),
                ('post_script', models.CharField(max_length=200, null=True, verbose_name='订单留言')),
                ('pay_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='订单金额')),
                ('status', models.IntegerField(choices=[(0, '正常'), (1, '禁用'), (2, '删除')], default=0, verbose_name='记录状态')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('order_status', models.SmallIntegerField(choices=[(0, '未接单'), (1, '已接单'), (2, '已配餐'), (3, '已取餐'), (4, '已评价')], default=1, verbose_name='订单状态')),
            ],
            options={
                'verbose_name': '订单信息',
                'verbose_name_plural': '订单信息',
            },
        ),
        migrations.CreateModel(
            name='order_foods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=1, verbose_name='数量')),
            ],
            options={
                'verbose_name': '订单商品',
                'verbose_name_plural': '订单商品',
            },
        ),
        migrations.CreateModel(
            name='shopcart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, '正常'), (1, '禁用'), (2, '删除')], default=0, verbose_name='记录状态')),
                ('nums', models.IntegerField(default=0, verbose_name='购买数量')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
                ('foods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_food', to='foods.Foods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '购物车喵',
                'verbose_name_plural': '购物车喵',
            },
        ),
    ]
