# Generated by Django 2.0.2 on 2018-07-18 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foods', '0002_auto_20180718_1224'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_seller', to=settings.AUTH_USER_MODEL, verbose_name='商家id'),
        ),
        migrations.AddField(
            model_name='shopcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL, verbose_name='用户id'),
        ),
        migrations.AddField(
            model_name='order_foods',
            name='foods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='o_food', to='foods.Foods', verbose_name='商品id'),
        ),
        migrations.AddField(
            model_name='order_foods',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='o_id', to='trades.order', verbose_name='订单id'),
        ),
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='o_sid', to=settings.AUTH_USER_MODEL, verbose_name='商家Id'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='o_uid', to=settings.AUTH_USER_MODEL, verbose_name='用户Id'),
        ),
        migrations.AlterUniqueTogether(
            name='shopcart',
            unique_together={('seller', 'user', 'foods')},
        ),
    ]
