# Generated by Django 2.0.2 on 2018-07-25 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spiders', '0002_amazon_goods_status'),
        ('users', '0002_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='code',
        ),
        migrations.RemoveField(
            model_name='news',
            name='mobile',
        ),
        migrations.AddField(
            model_name='news',
            name='content',
            field=models.TextField(default=0, max_length=255, verbose_name='消息内容'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='good',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='good_id', to='spiders.amazon_goods', verbose_name='指向商品的外键'),
            preserve_default=False,
        ),
    ]
