# Generated by Django 2.0.2 on 2018-07-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180725_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(default='无', max_length=255, verbose_name='消息内容'),
        ),
    ]
